const data = {
    products:[
        {
            _id:'1',
            name:'Slim Shirt',
            category: 'Shirts',
            image:'/images/th.jpg',
            price:80,
            brand:'Nike',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'fit Shirt',
            category: 'Shirts',
            image:'/images/11.jpeg',
            price:60,
            brand:'simple',
            rating: 4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste Free Shirt',
            category: 'Shirts',
            image:'/images/lacoste.jpg',
            price:120,
            brand:'Lacoste',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Coq sport fit pant',
            category: 'Shirts',
            image:'/images/th.jpg',
            price:150,
            brand:'coq sport',
            rating: 3.5,
            numReviews:9,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Rend Band Glass',
            category: 'eye Glass',
            image:'/images/11.jpeg',
            price:150,
            brand:'Rend Band',
            rating: 4.5,
            numReviews:12,
            description:'high quality product',
        },
    ],
};
export default data